services:
  telegram-bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DEFAULT_CHAT_ID=${DEFAULT_CHAT_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3